# Generated by Django 4.0.7 on 2022-10-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True)),
                ('input_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('multiselect', 'Multi Select'), ('file', 'File'), ('reference', 'Reference'), ('numeric', 'Numeric'), ('rich-text', 'Rich Text'), ('boolean', 'Boolean')], default='dropdown', max_length=50)),
                ('value_required', models.BooleanField(blank=True, default=False)),
                ('is_variant_only', models.BooleanField(blank=True, default=False)),
                ('visible_in_storefront', models.BooleanField(blank=True, default=True)),
                ('filterable_in_storefront', models.BooleanField(blank=True, default=False)),
                ('filterable_in_dashboard', models.BooleanField(blank=True, default=False)),
                ('storefront_search_position', models.IntegerField(blank=True, default=0)),
                ('available_in_grid', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='frontend.category')),
            ],
            options={
                'verbose_name': 'Attribute Name',
                'db_table': 'attribute_name',
            },
        ),
        migrations.CreateModel(
            name='VariationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Variation Theme')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pro_attr', models.ManyToManyField(related_name='pro_attr', to='variation.attributename', verbose_name='Attribute Name')),
            ],
            options={
                'verbose_name': 'Variation Theme',
                'verbose_name_plural': 'Variation Themes',
                'db_table': 'variation_theme',
            },
        ),
        migrations.CreateModel(
            name='DescriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='frontend.category')),
            ],
            options={
                'verbose_name': 'Description Type',
                'verbose_name_plural': 'Description Types',
                'db_table': 'description_type',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='variation.attributename')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'db_table': 'attribute_value',
            },
        ),
    ]
