# Generated by Django 4.0.7 on 2022-10-19 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format '+123456789'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=frontend.models.generateUUID, editable=False, unique=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('linkable', models.BooleanField(default=1)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('meta_keyword', models.TextField(blank=True, null=True)),
                ('cat_sample_img', models.ImageField(blank=True, max_length=50, null=True, upload_to='cat_img/%Y/%m/%d/')),
                ('cat_img', models.ImageField(blank=True, max_length=50, null=True, upload_to='cat_img/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='frontend.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category List',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
    ]
