# Generated by Django 4.0.7 on 2022-10-19 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('banner_img', models.ImageField(help_text='Field type:image.', null=True, upload_to='banner_img/%Y/%m/%d')),
                ('position', models.IntegerField(choices=[(1, 'Home Top'), (2, 'Home Left'), (3, 'Home Right'), (4, 'Home Header'), (5, 'Category Page')], default=1, help_text='Field type:select, Default:1, value:{dict(BANNER_POSITION)}', null=True)),
                ('offer_text', models.CharField(blank=True, help_text='Field type: string, Ex. 50% off', max_length=255, null=True)),
                ('offer_link', models.CharField(blank=True, help_text='Field type: string, Ex. Offer redirect link', max_length=255, null=True)),
                ('other_text', models.CharField(blank=True, help_text='Field type: string, Ex. Other information', max_length=255, null=True)),
                ('other_text_2', models.CharField(blank=True, help_text='Field type: string, Ex. Other information 2', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('category', models.JSONField(null=True, verbose_name='Category Ids')),
                ('product', models.JSONField(null=True, verbose_name='Product Ids')),
                ('discount_type', models.IntegerField(choices=[(0, '% Percentage'), (1, 'Fixed')], default=0, help_text='Field type:select, Default: % Percentage, value:{dict(DISCOUNT_TYPE)}', null=True)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('status', models.BooleanField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, help_text='Field type:boolean, Default: Active, value:{dict(STATUS_VALUE)}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='BannerText',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text_input', models.CharField(help_text='Field type: string.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revBannerText', to='addons.banner', verbose_name='Banner')),
            ],
            options={
                'verbose_name': 'Banner Text',
                'verbose_name_plural': 'Banner Text',
            },
        ),
    ]
