# Generated by Django 4.0.7 on 2022-10-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('order_note', models.TextField(blank=True, null=True)),
                ('order_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('tax', models.FloatField(blank=True, default=0.0, null=True)),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Accepted'), (3, 'Shipped'), (4, 'In Transit'), (5, 'Delivered'), (6, 'Completed'), (7, 'Cancelled')], default=1)),
                ('quantity', models.IntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relOrderAddressBook', to='accounts.addressbook')),
                ('apply_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relOrderApplyCouponCode', to='cart.applycouponcode')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_email', models.CharField(blank=True, max_length=254, null=True)),
                ('payer_fullname', models.CharField(blank=True, max_length=254, null=True)),
                ('payer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_address', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=254, verbose_name='Payment Status')),
                ('provider_order_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Order ID')),
                ('payment_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='Payment ID')),
                ('signature_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Signature ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relOrderOrderProduct', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
                'db_table': 'order_products',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relOrderPayment', to='orders.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relOrderAccount', to='accounts.account'),
        ),
    ]
